### ISSUE TITLE
add option in output group to retain oreginal file name

### ISSUE THREAD

**Issue by gregjozk** [jscholes/codex#3]
Hi,

as title say, is it possible to add an option to retain an oreginal file name. it will help me to organise my collection.

thanks.

**Comment by jscholes** [comment]
Thanks for your request.  I will add this to the list for version 2.2.

**Comment by jscholes** [comment]
The application is not actively maintained or supported.  Pre-built versions, and the corresponding project page, are no longer available.  As such, this will not likely be worked on.
