### ISSUE TITLE
msvcr100.dll not found on new Windows 10 installation

### ISSUE THREAD

**Issue by ndarilek** [jscholes/codex#5]
I'm a Linux user running Windows 10 in a VM in part so I can use Codex. Unfortunately, launching Codex fails because msvcr100.dll can't be found.

Google led me to the Visual C redistributable runtime, which I installed just in case that was the issue. Nothing changed. I then placed c:\windows\system32\msvcr100.dll in the Codex app directory, which gave me a runtime error with an obscure hex code.

I'm not really a Windows person, so I don't know if there's an obvious fix, or if having the hex code in the runtime error would help. I can try getting it to you if so--I don't have cut-and-paste working between the VM and host at the moment, which is why I haven't included it directly.

Overall the Win10 installation seems stable and hasn't given me any other issues, so I'm wondering if perhaps I need a specific version of msvcr100.dll installed? Again, I'm not a Windows person, but I recall having at least half a dozen installed at one point. I don't know if each of those was actually in use, or if the older versions were just artifacts of the package installation system.

This is a brand new installation as of yesterday onto a blank VM drive, with all updates applied.

Thanks for your help.

**Comment by jscholes** [comment]
You will need the 32-bit Microsoft Visual C++ 2015 Redistributable installed to run Codex.  It's possible that you downloaded a 64-bit version, or a newer or older release.  Here's the download link:

https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

**Comment by ndarilek** [comment]
Thanks. I downloaded/installed the DLL from the link you posted. No
change, even after a reboot and re-install of Codex.

**Comment by jscholes** [comment]
In your original comment you mentioned dropping a copy of msvcr100.dll into the Codex directory.  Please ensure that the reinstallation of Codex definitely removed it as it won't work there.

**Comment by jscholes** [comment]
Additionally, it may help to remove any other copies of the Microsoft C++ Redistributable that you no longer need.

**Comment by ndarilek** [comment]
Ah, thanks, I'll give that a shot. Do you specifically need the 2015
version, or will that or anything newer suffice? I don't know how
Windows handles the case where multiple versions of the runtime are
installed.

Thanks for the help.

**Comment by ndarilek** [comment]
Thanks, forgot to mention I'd removed it myself before trying again.

**Comment by ndarilek** [comment]
Interestingly enough, when I uninstall the 2010 runtime, and only have
the 2015 runtime installed, searching my system for msvc100.dll comes up
blank in all system locations. When I manually poke around in
\windows\system or \windows\system32, I don't see msvcr100.dll either.

The only copy I find is in an installed game. When I place *that* in the
codex directory, instead of a crash with an odd hex code, I supposedly
get an error log of some sort. I can send this to you if you like, but
given that I'm just using some random person's DLL, I don't know how
useful it might be. :)

Thoughts on what else I might try?

**Comment by jscholes** [comment]
The application is not actively maintained or supported.  Pre-built versions, and the corresponding project page, are no longer available.  As such, this will not likely be worked on.
